In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import numpy as np
from sklearn import preprocessing

In [2]:
df = pd.read_csv("prova_iris.csv")

In [3]:
print(df.shape)

(150, 5)


In [4]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  148 non-null    float64
 3   petal_width   147 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None


In [24]:
df.head

<bound method NDFrame.head of      sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]>

In [5]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    2
petal_width     3
species         0
dtype: int64

In [6]:
df_setosa=df.query("species=='setosa'")

In [7]:
print(df_setosa.info())
print(df_setosa.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  50 non-null     float64
 1   sepal_width   50 non-null     float64
 2   petal_length  49 non-null     float64
 3   petal_width   48 non-null     float64
 4   species       50 non-null     object 
dtypes: float64(4), object(1)
memory usage: 2.3+ KB
None
sepal_length    0
sepal_width     0
petal_length    1
petal_width     2
species         0
dtype: int64


In [8]:
previsor = df.iloc[:, 0:3].values
classe = df.iloc[:, 4].values 

In [9]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

num_pipeline = Pipeline([
                         ('imputer', SimpleImputer(strategy="mean")),
                         ])

In [10]:
previsor = num_pipeline.fit_transform(previsor)

In [11]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [13]:
x_treino, x_teste, y_treino, y_teste = train_test_split(previsor, classe, test_size = 0.3, random_state = 1)

In [14]:
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

modelonb = GaussianNB()
modelonb = modelonb.fit(x_treino, y_treino)
preditornb = modelonb.predict(x_teste)


modelotree = DecisionTreeClassifier()
modelotree = modelotree.fit(x_treino, y_treino)
preditortree = modelotree.predict(x_teste)

In [15]:
from sklearn.metrics import confusion_matrix
taxa_acerto = accuracy_score(y_teste, preditornb)
taxa_erro = 1 - taxa_acerto
print("Naive Bayes")
print("Taxa de acerto:")
print(taxa_acerto)
print("Taxa de erro:")
print(taxa_erro)
print("-------")
print(confusion_matrix(y_teste,preditornb))

taxa_acerto = accuracy_score(y_teste, preditortree)
taxa_erro = 1 - taxa_acerto
print("Arvore")
print("Taxa de acerto:")
print(taxa_acerto)
print("Taxa de erro:")
print(taxa_erro)
print("-------")
print(confusion_matrix(y_teste,preditortree))

Naive Bayes
Taxa de acerto:
0.9111111111111111
Taxa de erro:
0.0888888888888889
-------
[[14  0  0]
 [ 0 16  2]
 [ 0  2 11]]
Arvore
Taxa de acerto:
0.9555555555555556
Taxa de erro:
0.0444444444444444
-------
[[14  0  0]
 [ 0 17  1]
 [ 0  1 12]]
